### ISSUE TITLE
update attachment file locations

### ISSUE THREAD

**Issue by ollehints** [geocollections/eurocore#3]
Attachment files, including drillcore images should be placed to folders like this: /files/fc/fc934801-a663-49d6-87b0-693ee8aab00a.jpg
If files are images (jpg, png) then previews (width 400px, 1000px and 2000px) should be created in folders like this: 
* /files/small/fc/fc934801-a663-49d6-87b0-693ee8aab00a.jpg
* /files/medium/fc/fc934801-a663-49d6-87b0-693ee8aab00a.jpg
* /files/large/fc/fc934801-a663-49d6-87b0-693ee8aab00a.jpg

**Comment by urtson** [comment]
Files are now in /home/eurocore/files, pointed by a symlink /var/www/eurocore/files:
/files/7b/7b3feffb-8d9b-4a42-b44b-edec43e40f5b.jpg
and resized previews in subfolders:
/files/7b/400/7b3feffb-8d9b-4a42-b44b-edec43e40f5b.jpg
/files/7b/1000/7b3feffb-8d9b-4a42-b44b-edec43e40f5b.jpg
/files/7b/2000/7b3feffb-8d9b-4a42-b44b-edec43e40f5b.jpg
